jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make Gradle wrapper executable
        working-directory: ./android
        run: chmod +x ./gradlew

      # YAHAN HUMNE NAYA STEP ADD KIYA HAI 👇
      - name: Fix Merge Conflict Automatically
        working-directory: ./android/app
        # Ye command apne aap file ke end mein zaroori code add kar degi
        run: |
          echo "" >> build.gradle.kts
          echo "android { packaging { jniLibs { pickFirsts.add(\"**/libonnxruntime.so\") } } }" >> build.gradle.kts

      - name: Build Release APK
        working-directory: ./android
        run: ./gradlew assembleRelease

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: LLM-Hub-Release-Unsigned
          path: android/app/build/outputs/apk/release/*.apk
